- name: Users | Jeffrey | check if AccountsService entry exists
  tags: users,jeffrey
  ansible.builtin.stat:
    path: /var/lib/AccountsService/users/jeffrey
  register: p

- name: Users | Jeffrey | create AccountsService entry
  tags: users,jeffrey
  ansible.builtin.copy:
    src: users/AccountsService_user
    dest: /var/lib/AccountsService/users/jeffrey
    owner: root
    group: root
    mode: '0600'
  when: p.stat.isreg is not defined

- name: Users | Jeffrey | Copy profile image
  tags: dotfiles,dotfiles-jeffrey
  ansible.builtin.copy:
    src: users/profile_images/jeffrey.png
    dest: /var/lib/AccountsService/icons/jeffrey
    owner: root
    group: root
    mode: '0644'

- name: Users | Jeffrey | Set profile image
  tags: dotfiles,dotfiles-jeffrey
  ansible.builtin.lineinfile:
    path: /var/lib/AccountsService/users/jeffrey
    regexp: '^Icon='
    line: Icon=/var/lib/AccountsService/icons/jeffrey

- name: Users | Jeffrey | Enable podman socket
  become_user: jeffrey
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    scope: user

- name: Include tasks | Flatpaks
  ansible.builtin.include_tasks: users/jeffrey/software/{{ item }}.yml
  with_items:
    - flathub
    - google_chrome
    - vscode

- name: Include tasks | GNOME settings
  ansible.builtin.include_tasks: users/jeffrey/gnome/{{ item }}.yml
  with_items:
    - keyboard_shortcuts
    - peripherals

- name: Import tasks | VPN Client - PIA Seattle
  ansible.builtin.import_tasks: users/jeffrey/vpn_client.yml
