- name: users | jeffrey | check if AccountsService entry exists
  tags: users,jeffrey
  stat:
    path: /var/lib/AccountsService/users/jeffrey
  register: p

- name: users | jeffrey | create AccountsService entry
  tags: users,jeffrey
  copy:
    src: users/AccountsService_user
    dest: /var/lib/AccountsService/users/jeffrey
    owner: root
    group: root
    mode: 0600
  when: p.stat.isreg is not defined

- name: users | jeffrey | copy profile image
  tags: dotfiles,dotfiles-jeffrey
  copy:
    src: users/jeffrey/profile_image.png
    dest: /var/lib/AccountsService/icons/jeffrey
    owner: root
    group: root
    mode: 0644

- name: users | jeffrey | set profile image
  tags: dotfiles,dotfiles-jeffrey
  lineinfile:
    path: /var/lib/AccountsService/users/jeffrey
    regexp: '^Icon='
    line: Icon=/var/lib/AccountsService/icons/jeffrey

- name: users | jeffrey | transmission | check if settings.json exists
  stat:
    path: /home/jeffrey/.config/transmission/settings.json
  register: p

- name: users | jeffrey | tranmission | disable ipv6
  lineinfile:
    path: /home/jeffrey/.config/transmission/settings.json
    regex: '^    "bind-address-ipv6": "::",$'
    line: '    "bind-address-ipv6": "fe80::",'
    validate: 'python -m json.tool %s'
  when: p.stat.isreg is defined and p.stat.isreg

- include_tasks: backup.yml

- include_tasks: profile_sync_daemon.yml
  when:
    - profile_sync_daemon
    - ansible_distribution in ["Archlinux", "Debian", "Fedora", "openSUSE Tumbleweed", "Ubuntu"]