- name: Load vpn credentials variables
  include_vars: vpn_credentials.yml

- name: Docker | Add official docker repo (CentOS)
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  when: ansible_distribution == "CentOS"

- name: Docker | Install required packages (CentOS)
  ansible.builtin.package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  when: ansible_distribution == "CentOS"

- name: Docker | Install required packages
  ansible.builtin.package:
    state: present
    name:
      - "{{ docker_package }}"
      - "{{ docker_compose_package }}"
  when: ansible_distribution != "CentOS"


- name: Docker | Install docker-compose-switch (openSUSE Tumbleweed)
  ansible.builtin.package:
    state: present
    name: docker-compose-switch
  when: ansible_distribution == "openSUSE Tumbleweed"

- name: Docker | Ensure group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker | Add jeffrey to docker group
  ansible.builtin.user:
    name: jeffrey
    groups: docker
    append: yes

- name: Docker | Enable docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes

- name: Docker | Create folder for docker data
  ansible.builtin.file:
    path: "{{ docker.data_dir }}"
    state: directory

- name: Docker | Create directories
  ansible.builtin.file:
    path: '/{{zfs_pool.pool_name}}/docker/{{ item.dir }}'
    state: directory
  with_items:
    - { dir: 'data/config' }
    - { dir: 'data/config/vpn' }
    - { dir: 'compose' }

- name: Docker | Copy VPN config
  ansible.builtin.copy:
    src: docker/vpn.conf
    dest: "{{ docker.data_dir }}/config/vpn/vpn.conf"

- name: Docker | VPN authentication credentials
  ansible.builtin.template:
    src: docker/vpn_auth.j2
    dest: "{{ docker.data_dir }}/config/vpn/vpn.auth"

- name: Docker | Setup docker .env file
  ansible.builtin.template:
    src: docker/env.j2
    dest: '/{{zfs_pool.pool_name}}/docker/compose/.env'

- name: Docker | Copy docker-compose.yml
  ansible.builtin.copy:
    src: docker/compose.yml
    dest: '/{{zfs_pool.pool_name}}/docker/compose/docker-compose.yml'

- name: Docker | Start services
  ansible.builtin.command: docker compose up -d
  args:
    chdir: '/{{zfs_pool.pool_name}}/docker/compose'
