---
roles:
  # Install a role from Ansible Galaxy.
  - name: artis3n.tailscale

collections:
  # Install collections from Ansible Galaxy.
  - name: ansible.posix
  - name: community.general
  - name: kewlfft.aur