---
- name: zypper_refresh
  community.general.zypper_repository:
    repo: '*'
    auto_import_keys: true
    runrefresh: yes

- name: load_zfs_kmod
  community.general.modprobe:
    name: zfs
    state: present