- name: thinkpad | peripherals | keyboard | enable compose key
  tags: thinkpad,gnome,keyboard,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['lv3:rwin_switch', 'compose:prsc']"
  changed_when: false