---
- name: restart_sshd # noqa name
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    state: restarted

- name: rpm-ostree_reload # noqa name
  ansible.builtin.command: rpm-ostree reload

- name: systemd_daemon_reload # noqa name
  ansible.builtin.systemd:
    daemon_reload: true
