---
- name: apt_refresh
  ansible.builtin.apt: update_cache=yes
  changed_when: False

- name: zypper_refresh
  community.general.zypper_repository:
    repo: '*'
    runrefresh: yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: restart_fail2ban
  service:
    name: fail2ban
    state: restarted