---
- name: zypper_refresh
  community.general.zypper_repository:
    repo: '*'
    auto_import_keys: true
    runrefresh: yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted