---
- name: apt_refresh
  ansible.builtin.apt: update_cache=yes
  changed_when: False
  when: ansible_os_family == "Debian"

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: restart_fail2ban
  service:
    name: fail2ban
    state: restarted