- name: users | josh | copy profile image
  tags: dotfiles,dotfiles-josh
  copy:
    src: users/josh/profile_image.png
    dest: /var/lib/AccountsService/icons/josh
    owner: root
    group: root
    mode: 0644

- name: users | josh | check if user has logged in before
  tags: users,josh
  stat:
    path: /var/lib/AccountsService/users/josh
  register: p

- name: users | josh | create AccountsService/users/username
  tags: users,josh
  copy:
    src: users/AccountsService_user
    dest: /var/lib/AccountsService/users/josh
    owner: root
    group: root
    mode: 0600
  when: p.stat.isreg is not defined

- name: users | josh | set profile image
  tags: dotfiles,dotfiles-josh
  lineinfile:
    path: /var/lib/AccountsService/users/josh
    regexp: '^Icon='
    line: Icon=/var/lib/AccountsService/icons/josh

- name: users | josh | create ~/.config directory
  tags: dotfiles,josh,users
  file:
    path: /home/josh/.config
    state: directory
    owner: josh
    group: "{{ user_group_name | default('josh') }}"
    mode: 0700

- name: users | josh | create ~/.config/autostart directory
  tags: dotfiles,josh,users
  file:
    path: /home/josh/.config/autostart
    state: directory
    owner: josh
    group: "{{ user_group_name | default('josh') }}"
    mode: 0755

- name: users | josh | check if chrome is set to autostart
  tags: users,josh,google-chrome
  stat:
    path: /home/josh/.config/autostart/google-chrome.desktop
  register: q

- name: users | josh | enable chrome autostart
  tags: users,josh,google-chrome
  file:
    src: /usr/share/applications/google-chrome.desktop
    dest: /home/josh/.config/autostart/google-chrome.desktop
    owner: josh
    group: "{{ user_group_name | default('josh') }}"
    state: link
  when:
    - q.stat.islnk is not defined

# GNOME config
- name: users | josh | GNOME | enable natural scrolling (mouse)
  tags: gnome,mouse,peripherals
  become: true
  become_user: josh
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: users | josh | GNOME | enable natural scrolling (touchpad)
  tags: gnome,mouse,peripherals
  become_user: josh
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"

- name: users | josh | GNOME | enable tap to click (touchpad)
  tags: gnome,touchpad,peripherals
  become_user: josh
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: users | josh | GNOME | enable two finger scrolling  (touchpad)
  tags: gnome,touchpad,peripherals
  become_user: josh
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"

- name: users | josh | GNOME | read favorite apps
  become_user: josh
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: favorite_apps

- name: users | josh | GNOME | set favorite apps (Fedora)
  tags: gnome,users,josh
  become_user: josh
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
  when:
    - ansible_distribution == "Fedora"
    - not favorite_apps.value

- name: users | josh | GNOME | disable ABRT notifications (Red Hat)
  tags: gnome,users,josh
  become_user: josh
  dconf:
    key: "/org/gnome/desktop/notifications/application/org-freedesktop-problems-applet/enable"
    value: "false"
  when: ansible_os_family == "RedHat"

- name: users | josh | GNOME | enable location services
  tags: gnome,users,josh
  become_user: josh
  dconf:
    key: "/org/gnome/system/location/enabled"
    value: "true"