- name: users | nelu | copy profile image
  tags: dotfiles,dotfiles-nelu
  copy:
    src: users/nelu/profile_image.png
    dest: /var/lib/AccountsService/icons/nelu
    owner: root
    group: root
    mode: 0644

- name: users | nelu | check if user has logged in before
  tags: users,nelu
  stat:
    path: /var/lib/AccountsService/users/nelu
  register: p

- name: users | nelu | set profile image
  tags: dotfiles,dotfiles-nelu
  lineinfile:
    path: /var/lib/AccountsService/users/nelu
    regexp: '^Icon='
    line: Icon=/var/lib/AccountsService/icons/nelu
  when: p.stat.isreg is defined

- name: users | nelu | create config/autostart directory
  tags: dotfiles,nelu,users
  file:
    path: /home/nelu/.config/autostart
    state: directory
    owner: nelu
    group: "{{ user_group_name | default('nelu') }}"
    mode: 0755
  when: p.stat.isreg is defined

- name: users | nelu | check if chrome is set to autostart
  tags: users,nelu,google-chrome
  stat:
    path: /home/nelu/.config/autostart/google-chrome.desktop
  register: q
  when: p.stat.isreg is defined

- name: users | nelu | enable chrome autostart
  tags: users,nelu,google-chrome
  file:
    src: /usr/share/applications/google-chrome.desktop
    dest: /home/nelu/.config/autostart/google-chrome.desktop
    owner: nelu
    group: "{{ user_group_name | default('nelu') }}"
    state: link
  when:
    - q.stat.islnk is not defined
    - p.stat.isreg is defined

# GNOME config
- name: users | nelu | GNOME | enable natural scrolling (mouse)
  tags: gnome,mouse,peripherals
  become: true
  become_user: nelu
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: users | nelu | GNOME | enable natural scrolling (touchpad)
  tags: gnome,mouse,peripherals
  become_user: nelu
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"

- name: users | nelu | GNOME | enable tap to click (touchpad)
  tags: gnome,touchpad,peripherals
  become_user: nelu
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: users | nelu | GNOME | enable two finger scrolling  (touchpad)
  tags: gnome,touchpad,peripherals
  become_user: nelu
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"

- name: users | nelu | GNOME | read favorite apps
  become_user: nelu
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: favorite_apps

- name: users | nelu | GNOME | set favorite apps (Fedora)
  tags: gnome,users,nelu
  become_user: nelu
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
  when:
    - ansible_distribution == "Fedora"
    - not favorite_apps.value

- name: users | nelu | GNOME | disable ABRT notifications (Red Hat)
  tags: gnome,users,nelu
  become_user: nelu
  dconf:
    key: "/org/gnome/desktop/notifications/application/org-freedesktop-problems-applet/enable"
    value: "false"
  when: ansible_os_family == "RedHat"

- name: users | nelu | GNOME | enable location services
  tags: gnome,users,nelu
  become_user: nelu
  dconf:
    key: "/org/gnome/system/location/enabled"
    value: "true"