- name: Load distro-specific variables
  tags: always
  include_vars: "{{ ansible_distribution }}.yml"

- block:
  ## enable repositories
  - import_tasks: software/repositories.yml
  - import_tasks: software/flathub.yml

  ## install software
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/packages.yml
  - import_tasks: software/packages_flatpak.yml
  - import_tasks: software/vscode.yml

  ## vpn client setup
  - include_tasks: vpn_client.yml
    when: vpn_client

  ## User configs
  - import_tasks: users/ana.yml
    when: user_ana
  - import_tasks: users/jeffrey.yml
  - import_tasks: users/josh.yml
    when: user_josh
  - import_tasks: users/nelu.yml
    when: user_nelu

  ## desktop environment
  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome
  - include_tasks: desktop_environments/gnome/peripherals.yml
    when: gnome
  - include_tasks: desktop_environments/gnome/software_settings.yml
    when: gnome

  rescue:
  - name: Set fact if task failed
    set_fact: task_failed=true