- name: Workstation configuration
  block:

    # Needed for some flatpak operations
    - name: Workstation | Install dbus-x11
      community.general.rpm_ostree_pkg:
        name: dbus-x11
        state: present

  # User configs
    - name: Import tasks | Users | Jeffrey
      ansible.builtin.import_tasks: users/jeffrey/jeffrey.yml

    - name: Include tasks | Additional users
      ansible.builtin.include_tasks: users/additional_users.yml
      with_dict: "{{ additional_users }}"
      when: additional_users is defined

  rescue:
    - name: Set fact if task failed
      ansible.builtin.set_fact:
        task_failed: true
