- name: software | workstation packages | install packages
  tags: packages,workstation
  package:
    state: present
    name:
      - vlc

- name: software | workstation packages | install ansible-lint
  tags: packages,workstation
  package:
    state: present
    name: "{{ ansible_lint_package }}"
  when: ansible_lint_package is defined

- name: software | workstation packages | install toolbox (Red Hat)
  tags: packages,workstation
  package:
    state: present
    name: toolbox
  when:
    - ansible_os_family == "RedHat"
    - toolbox_install

- name: software | workstation packages | install virt-manager, libvirt-client
  tags: packages,workstation
  package:
    state: present
    name:
      -  virt-manager
      - "{{ libvirt_client_package }}"
  when: virt_manager_install
