- name: software | flatpak | flatpak repair
  command:
    cmd: /usr/bin/flatpak repair --system
  changed_when: false

- name: software | flatpak | remove flatpack packages
  flatpak:
    name: "{{ item }}"
    state: absent
  loop:
    - com.transmissionbt.Transmission

- name: software | flatpak | update flatpak packages
  command:
    cmd: /usr/bin/flatpak update --system --noninteractive
  register: flatpak_update_result
  changed_when: flatpak_update_result is not search('Nothing to do.')

- name: software | flatpak | install base flatpack packages
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
    - com.discordapp.Discord
    - com.spotify.Client
    - org.signal.Signal

- name: software | flatpak | install Minecraft flatpack
  flatpak:
    name: com.mojang.Minecraft
    state: present
    remote: flathub
  when: minecraft_install | bool