- name: software | workstation packages | install packages
  tags: packages,workstation
  package:
    state: present
    name:
      - transmission-gtk
      - vlc

- name: software | workstation packages | install ansible-lint
  tags: packages,workstation
  package:
    state: present
    name: "{{ ansible_lint_package }}"
  when: ansible_lint_package is defined

- name: software | workstation packages | install deja-dup
  tags: packages,workstation
  package:
    state: present
    name: "{{ deja_dup_package }}"
  when: deja_dup_package is defined

- name: software | workstation packages | install toolbox (Red Hat)
  tags: packages,workstation
  package:
    state: present
    name: toolbox
  when:
    - ansible_os_family == "RedHat"
    - toolbox_install

- name: software | workstation packages | install virt-manager
  tags: packages,workstation
  package:
    state: present
    name: virt-manager
  when: virt_manager_install