- name: software | flatpak | flatpak repair
  command:
    cmd: /usr/bin/flatpak repair --system
  changed_when: false

- name: software | flatpak | install flatpack packages
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
    - com.belmoussaoui.Authenticator
    - com.discordapp.Discord
    - com.mojang.Minecraft
    - com.spotify.Client
    - com.valvesoftware.Steam
    - org.gimp.GIMP
    - org.signal.Signal

- name: software | flatpak | update flatpak packages
  command:
    cmd: /usr/bin/flatpak update --system --noninteractive
  register: flatpak_update_result
  changed_when: flatpak_update_result is not search('Nothing to do.')