- name: system setup | repositories | add rpm fusion free repository (fedora)
  tags: rpmfusion,repositories
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  when: ansible_distribution == "Fedora"

- name: system setup | repositories | add rpm fusion non-free repository (fedora)
  tags: rpmfusion,repositories
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  notify: rpmfusion_appstream_metadata
  when: ansible_distribution == "Fedora"

- name: system setup | repositories | add packman repository (opensuse)
  tags: packman,repositories
  zypper_repository:
    name: packman
    repo: 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/'
    auto_import_keys: yes
    priority: 90
    autorefresh: true
  notify: packman_vendor_change
  when: ansible_distribution == "openSUSE Tumbleweed"