- name: system setup | repositories | add rpm fusion free repository (fedora)
  tags: rpmfusion,repositories
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  when: ansible_distribution == "Fedora"

- name: system setup | repositories | add rpm fusion non-free repository (fedora)
  tags: rpmfusion,repositories
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  notify: rpmfusion_appstream_metadata
  when: ansible_distribution == "Fedora"

- name: system setup | repositories | add rpm fusion free repository (centos)
  tags: rpmfusion,repositories
  dnf:
    name: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  when: ansible_distribution == "CentOS"

- name: system setup | repositories | add rpm fusion non-free repository (centos)
  tags: rpmfusion,repositories
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  notify: rpmfusion_appstream_metadata
  when: ansible_distribution == "CentOS"

- name: system setup | repositories | add packman repository (opensuse tumbleweed)
  tags: packman,repositories
  zypper_repository:
    name: packman
    repo: 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/'
    auto_import_keys: yes
    priority: 90
    autorefresh: true
  notify: packman_vendor_change
  when: ansible_distribution == "openSUSE Tumbleweed"

- name: system setup | repositories | add packman repository (opensuse leap)
  tags: packman,repositories
  zypper_repository:
    name: packman
    repo: "https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_{{ ansible_distribution_version }}/"
    auto_import_keys: yes
    priority: 90
    autorefresh: true
  notify: packman_vendor_change
  when: ansible_distribution == "openSUSE Leap"

- name: system setup | repositories | enable multilib repository (arch)
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"
  when:
    - ansible_os_family == "Archlinux"
    - ansible_architecture == "x86_64"
    - steam_install == "native"

- name: system setup | repositories | enable multilib repository (arch)
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"
  notify: pacman_refresh
  when:
    - ansible_os_family == "Archlinux"
    - ansible_architecture == "x86_64"
    - steam_install == "native"

- name: system setup | repositories | enable multilib (x86) (debian)
  ansible.builtin.command: dpkg --add-architecture i386
  notify: apt_refresh
  when:
    - ansible_distribution == "Debian"
    - ansible_architecture == "x86_64"
    - steam_install == "native"