- name: trigger package cache refresh if needed
  meta: flush_handlers
  when: steam_install == "native"

- name: gather package facts
  ansible.builtin.package_facts:
  when:
    - ansible_distribution == "Debian"
    - steam_install == "native"

- name: software | steam | agree to steam license (debian)
  debconf:
    name: steam
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - { question: 'steam/license', value: '', vtype: 'note'}
    - { question: 'steam/question', value: 'I AGREE', vtype: 'select'}
  when:
    - "'steam' not in ansible_facts.packages"
    - ansible_distribution == "Debian"
    - steam_install == "native"

- name: software | steam | install via native package
  package:
    name: "{{ steam_package }}"
    state: present
  when: steam_install == "native"

- name: software | steam | install via flatpack
  flatpak:
    name: com.valvesoftware.Steam
    state: present
    remote: flathub
  when: steam_install == "flatpak"

- name: software | steam | remove flatpak if installed
  flatpak:
    name: com.valvesoftware.Steam"
    state: absent
  when: steam_install != "flatpak"