- name: software | vscode | add repository (fedora)
  tags: vscode,repositories,software,workstation
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  when: ansible_os_family == "RedHat"

- name: software | vscode | add repository key (debian)
  tags: vscode,repositories,software,workstation
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  when: ansible_os_family == "Debian"

- name: software | vscode | add repository (debian)
  tags: vscode,repositories,software,workstation
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode
  when: ansible_os_family == "Debian"

- name: software | vscode | add repository key (suse)
  tags: vscode,repositories,software,workstation
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
    state: present
  when: ansible_os_family == "Suse"

- name: software | vscode | add repository (suse)
  tags: vscode,repositories,software,workstation
  zypper_repository:
    name: code
    repo: https://packages.microsoft.com/yumrepos/vscode
    state: present
  when: ansible_os_family == "Suse"

- name: software | vscode | install package
  package:
    state: present
    name: code
