amd_microcode_package: amd-ucode
intel_microcode_package: intel-ucode
lm_sensors_package: lm_sensors
openssh_package: openssh
openssh_service: sshd
powerline_fonts_package: powerline-fonts
python_psutil_package: python-psutil
vim_package: vim