ansible_package: ansible-core
automatic_updates_timer: rpm-ostreed-automatic.timer
openssh_package: openssh
openssh_service: sshd
powerline_fonts_package: powerline-fonts
python_psutil_package: python3-psutil
vim_package: vim-enhanced
