- name: Dreamhost DDNS | Copy script
  ansible.builtin.copy:
    src: dreamhost_ddns.sh
    dest: /usr/local/sbin/dreamhost_ddns.sh
    owner: root
    group: root
    mode: '0550'

- name: Dreamhost DDNS | Place service unit
  ansible.builtin.template:
    src: ddns_service.j2
    dest: /etc/systemd/system/dreamhost_ddns.service
    owner: root
    group: root
    mode: '0640'

- name: Dreamhost DDNS | Place timer unit
  ansible.builtin.template:
    src: ddns_timer.j2
    dest: /etc/systemd/system/dreamhost_ddns.timer
    owner: root
    group: root
    mode: 'c0640'

- name: Dreamhost DDNS | Enable systemd timer
  ansible.builtin.systemd:
    name: dreamhost_ddns.timer
    enabled: true
