- name: Firewall | Install custom firewalld services
  ansible.builtin.copy:
    src: 'firewall/{{ item }}.xml'
    dest: '/etc/firewalld/services/{{ item }}.xml'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - bazarr
    - deluge
    - homeassistant
    - jackett
    - radarr
    - sonnar
  register: firewall_service_installed

- name: Firewall | Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  when: firewall_service_installed.changed

- name: Firewall | Open ports
  ansible.posix.firewalld:
    zone: public
    service: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - bazarr
    - deluge
    - homeassistant
    - jackett
    - plex
    - radarr
    - samba
    - sonnar

# Too much effort to find individual ports for Home Assistant
# We're behind router firewall anyways...
- name: Firewall | Match Fedora's open ports (SUSE)
  ansible.posix.firewalld:
    zone: public
    port: '1025-65535/{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - tcp
    - udp
  when: ansible_os_family == "Suse"