- name: Load distro-specific variables
  tags: always
  include_vars: "{{ ansible_distribution }}.yml"

- block:
  - import_tasks: zfs.yml
  - import_tasks: docker/docker.yml
  - import_tasks: dreamhost_ddns.yml
    when:
      - dreamhost_ddns.enabled is defined
      - dreamhost_ddns.enabled | bool
  - import_tasks: packages.yml

  rescue:
  - name: Set fact if task failed
    set_fact: task_failed=true