- name: gnome | keyboard shortcuts | open home dir (super+e)
  tags: workstation,gnome,keyboard-shortcuts
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>e']"
  changed_when: false

- name: gnome | keyboard shortcuts | enable custom keybindings
  tags: workstation,gnome,keyboard-shortcuts
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
  changed_when: false
  when: ansible_distribution != "Ubuntu"

- name: gnome | keyboard shortcuts | launch terminal (ctl+alt+t)
  tags: workstation,gnome,keyboard-shortcuts
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: 'binding' , value: "'<Primary><Alt>t'" }
    - { key: 'command' , value: "'gnome-terminal'" }
    - { key: 'name' , value: "'Launch terminal'" }
  changed_when: false
  when: ansible_distribution != "Ubuntu"