- name: gnome | packages | install gnome packages (all)
  tags: gnome,gnome-packages
  package:
    name:
      - gnome-tweaks
      - seahorse
      - transmission-gtk

- name: gnome | packages | install gnome packages (fedora)
  tags: gnome,gnome-packages
  package:
    name:
      - gnome-backgrounds-extras
      - "{{ gnome_extensions_app_package }}"
  when: ansible_distribution == "Fedora"

- name: gnome | packages | install deja-dup
  tags: packages,workstation,gnome,backup
  package:
    state: present
    name: "{{ deja_dup_package }}"
  when: deja_dup_package is defined