- name: gnome | peripherals | enable natural scrolling (mouse)
  tags: gnome,mouse,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: gnome | peripherals | enable natural scrolling (touchpad)
  tags: gnome,mouse,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"

- name: gnome | peripherals | enable tap to click (touchpad)
  tags: gnome,mouse,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: gnome | peripherals | enable two finger scrolling  (touchpad)
  tags: gnome,mouse,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"

- name: gnome | peripherals | increase cursor speed (mouse)
  tags: gnome,mouse,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/speed"
    value: "0.00000000000000000"
  changed_when: false

- name: gnome | peripherals | increase cursor speed (touchpad)
  tags: gnome,mouse,peripherals
  become_user: jeffrey
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/speed"
    value: "0.43333333333333333"
  changed_when: false

- name: gnome | peripherals | set manual night-light schedule
  tags: gnome,peripherals,night-light
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "false"

- name: gnome | peripherals | set manual night-light schedule start time
  tags: gnome,peripherals,night-light
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
    value: "22.0"

- name: gnome | peripherals | set manual night-light schedule stop time
  tags: gnome,peripherals,night-light
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
    value: "6.0"

- name: gnome | peripherals | enable night-light
  tags: gnome,peripherals,night-light
  become_user: jeffrey
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"