- name: system setup | arch aur | create aur_builder user
  user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: system setup | arch aur | aur_builder sudo configuration
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'

- name: system setup | arch aur | install yay
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    state: latest