- name: System setup | Utilities | Install utility packages
  ansible.builtin.package:
    state: present
    name:
      - curl
      - fish
      - git
      - htop
      - neofetch
      - "{{ powerline_fonts_package }}"
      - tree
      - "{{ vim_package }}"
      - wol
