- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: present
    name:
      - at
      - colordiff
      - curl
      - fish
      - git
      - htop
      - "{{ lm_sensors_package }}"
      - neofetch
      - "{{ powerline_fonts_package }}"
      - pwgen
      - tree
      - "{{ vim_package }}"
