- name: System setup | Utilities | Install utility packages
  tags: packages,system,settings
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - colordiff
      - fish
      - htop
      - neofetch
      - "{{ powerline_fonts_package }}"
      - pwgen
      - "{{ vim_package }}"
