- name: system setup | repositories | enable powertools repository (centos)
  tags: powertools,repositories
  ini_file:
    path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
    section: powertools
    option: enabled
    value: "1"
    mode: 0644
  when: ansible_distribution == "CentOS"

# Note this only support CentOS Stream
- name: system setup | repositories | add epel repository (centos)
  tags: epel,repositories
  dnf:
    name:
      - epel-release
      - epel-next-release
    state: present
  when: ansible_distribution == "CentOS"

- name: system setup | repositories | add contrib non-free (debian)
  tags: contrib,non-free,debian,repositories
  ansible.builtin.template:
    src: software/debian_sourceslist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    validate: apt update -o dir::etc::sourcelist=%s
    backup: yes
  notify: apt_refresh
  when:
    - ansible_distribution == "Debian"
    - debian_enable_contrib_non_free