# Change Bluetooth controller mode to allow pair of Apple headphones
- name: ThinkPad | Bluetooth | Set controller mode bredr
  tags: thinkpad,configuration,bluetooth
  community.general.ini_file:
    dest: /etc/bluetooth/main.conf
    section: General
    option: ControllerMode
    value: bredr
    backup: false
    owner: root
    group: root
    mode: '0644'
