- name: thinkpad | tlp | add tlp repository (fedora)
  tags: thinkpad,repositories,tlp
  dnf:
    name: "https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  when:
    - tlp_kmod | bool
    - ansible_distribution == "Fedora"

- name: thinkpad | tlp | add tlp repository (ubuntu)
  tags: thinkpad,repositories,tlp
  apt_repository:
    repo: ppa:linrunner/tlp
  when:
    - tlp_kmod | bool
    - ansible_distribution == "Ubuntu"

- name: thinkpad | packages | install tlp
  tags: thinkpad,packages,tlp
  package:
    state: present
    name: tlp

- name: thinkpad | packages | install tlp kmod package
  tags: thinkpad,packages,tlp
  package:
    state: present
    name: "{{ tlp_kmod_package }}"
  when:
    - tlp_kmod | bool
    - ansible_distribution in ["Fedora", "Ubuntu"]

- name: gather package facts
  ansible.builtin.package_facts:

# Requires TLP version ≥ 1.3
# Not compatible with CentOS, Debian 10, or openSUSE Leap 15.2
- name: system setup | scripts | copy tlp charge-thresholds
  tags: thinkpad,tlp
  copy:
    src: tlp/charge_thresholds
    dest: /etc/tlp.d/01-charge-thresholds.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_facts.packages['tlp'][0].version is version('1.3', '>=')