---
- name: packman_vendor_change
  tags: packman,repositories,opensuse
  zypper:
    name: '*'
    state: dist-upgrade
    allow_vendor_change: true
    update_cache: yes
    extra_args: '--from packman'