---
- name: apt_refresh
  ansible.builtin.apt: update_cache=yes
  changed_when: False

- name: pacman_refresh
  community.general.pacman:
    update_cache: yes
  changed_when: False

- name: zypper_refresh
  community.general.zypper_repository:
    repo: '*'
    runrefresh: yes

- name: rpmfusion_appstream_metadata
  dnf:
    name: '@core'
    state: present

- name: packman_vendor_change
  tags: packman,repositories,opensuse
  community.general.zypper:
    name: "*"
    state: dist-upgrade
    allow_vendor_change: true
    extra_args: "--from packman"