---
- name: rpmfusion_appstream_metadata
  dnf:
    name: '@core'
    state: latest

- name: packman_vendor_change
  tags: packman,repositories,opensuse
  zypper:
    name: '*'
    state: dist-upgrade
    extra_args: '--from packman --allow-vendor-change'
    update_cache: no
