---
- name: apt_refresh
  ansible.builtin.apt: update_cache=yes
  changed_when: False

- name: pacman_refresh
  community.general.pacman:
    update_cache: yes
  changed_when: False

- name: rpmfusion_appstream_metadata
  dnf:
    name: '@core'
    state: present

- name: packman_vendor_change
  tags: packman,repositories,opensuse
  zypper:
    name: '*'
    state: dist-upgrade
    extra_args: '--from packman --allow-vendor-change'
    update_cache: no
