- name: Load distro-specific variables
  tags: always
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- block:
  # set up the ansible environment
  - import_tasks: ansible_setup.yml

  # enable repositories
  - import_tasks: software/repositories.yml

  # install software
  - import_tasks: software/packages_utilities.yml

  # basic user configuration
  - import_tasks: users/ana.yml
    when: user_ana
  - import_tasks: users/jeffrey/jeffrey.yml
  - import_tasks: users/josh.yml
    when: user_josh
  - import_tasks: users/nelu.yml
    when: user_nelu

  # perform remaining tasks:
  - import_tasks: system_setup/automatic_updates.yml
    when:  automatic_updates

  - import_tasks: system_setup/openssh.yml
    when: sshd

  - import_tasks: system_setup/fail2ban.yml
    when: fail2ban

  rescue:
  - name: Set fact if task failed
    set_fact: task_failed=true