version: "3.4"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      # - WATCHTOWER_NOTIFICATIONS=shoutrrr
      # - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:${PO_TOKEN}@${PO_USERKEY}

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - ${DATADIR}/config/gluetun:/gluetun
    ports:
      - 8112:8112
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER={{ vpn_client_username }}
      - OPENVPN_PASSWORD={{ vpn_client_password }}
      - SERVER_REGIONS=US Seattle
      - TZ=${TZ} # timezone, defined in .env

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:gluetun # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DATADIR}/downloads:/downloads # downloads folder
      - ${DATADIR}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${DATADIR}/config/jackett:/config # config files

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/config/sonarr:/config # config files
      - ${DATADIR}/complete/tv:/tv # tv shows folder
      - ${DATADIR}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/config/radarr:/config # config files
      - ${DATADIR}/complete/movies:/movies # movies folder
      - ${DATADIR}/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${DATADIR}/config/plex/db:/config # plex database
      - ${DATADIR}/config/plex/transcode:/transcode # temp transcoded files
      - ${DATADIR}/complete:/data # media library

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${DATADIR}/config/bazarr:/config # config files
      - ${DATADIR}/complete/movies:/movies # movies folder
      - ${DATADIR}/complete/tv:/tv # tv shows folder

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${DATADIR}/config/homeassitant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host