- block:
  - name: send failure notification via telegram
    tags: always
    telegram:
      token: "{{ telegram_token }}"
      chat_id: "{{ telegram_chat_id }}"
      msg_format: markdown
      msg: "⚠️  Provision failed on *{{ ansible_hostname }}*\n\n
        *Task*:  {{ ansible_failed_task.name }}\n
        *Action*: {{ ansible_failed_task.action }}\n
        *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```"
    changed_when: False

  - name: send distribution and version via telegram
    tags: always
    telegram:
      token: "{{ telegram_token }}"
      chat_id: "{{ telegram_chat_id }}"
      msg_format: markdown
      msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
    changed_when: False
    when: branch == "dev"

  rescue:
    - name: send failure notification via telegram
      tags: always
      telegram:
        token: "{{ telegram_token }}"
        chat_id: "{{ telegram_chat_id }}"
        msg_format: markdown
        msg: "⚠️  Provision failed on *{{ ansible_hostname }}*\n\n
          The specific error couldn't be shown, check the log."
      changed_when: False

    - name: send distribution and version via telegram
      tags: always
      telegram:
        token: "{{ telegram_token }}"
        chat_id: "{{ telegram_chat_id }}"
        msg_format: markdown
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
      changed_when: False
      when: branch == "dev"

- name: ansible job failed, clear cache to trigger another provision run
  ansible.builtin.systemd:
    name: ansible-refresh.service
    state: started