- name: system setup | automatic updates | install automatic updates package
  tags: automaticupdates,system,settings
  package:
    name: "{{ automatic_updates_package }}"
    state: present
  when: automatic_updates_package is defined

- name: system setup | automatic updates | Enable a timer for automatic updates
  tags: automaticupdates,system,settings
  systemd:
    name: "{{ automatic_updates_timer }}"
    state: started
    enabled: yes
  when: automatic_updates_timer is defined

- name: system setup | automatic updates | configure daily update cron job (opensuse leap)
  tags: automaticupdates,system,settings
  ansible.builtin.file:
    src: /usr/lib/YaST2/bin/online_update
    dest: /etc/cron.daily/opensuse.org-online_update
    owner: root
    group: root
    state: link
  when: ansible_distribution == "openSUSE Leap"

- name: system setup | automatic updates | configure aou - enable cron (opensuse leap)
  tags: automaticupdates,system,settings
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/automatic_online_update
    regexp: '^AOU_ENABLE_CRONJOB='
    line: AOU_ENABLE_CRONJOB="true"
  when: ansible_distribution == "openSUSE Leap"

- name: system setup | automatic updates | configure auo - install interactive (opensuse leap)
  tags: automaticupdates,system,settings
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/automatic_online_update
    regexp: '^AOU_SKIP_INTERACTIVE_PATCHES='
    line: AOU_SKIP_INTERACTIVE_PATCHES="false"
  when: ansible_distribution == "openSUSE Leap"

- name: system setup | automatic updates | configure auo options (opensuse leap)
  tags: automaticupdates,system,settings
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/automatic_online_update
    regexp: '^AOU_{{ item.option }}='
    line: AOU_{{ item.option }}="{{ item.value }}"
  with_items:
    - { option: 'ENABLE_CRONJOB', value: 'true' }
    - { option: 'SKIP_INTERACTIVE_PATCHES', value: 'false' }
    - { option: 'AUTO_AGREE_WITH_LICENSES', value: 'true' }
    - { option: 'INCLUDE_RECOMMENDS', value: 'false' }
    - { option: 'PATCH_CATEGORIES', value: '' }
  when: ansible_distribution == "openSUSE Leap"