- name: system setup | fail2ban | install daemon package
  tags: fail2ban,system,settings
  package:
    name: fail2ban
    state: present

- name: Users | Jeffrey | Check fail2ban install state
  ansible.builtin.shell: command -v fail2ban-client
  register: check_binary
  changed_when: false
  failed_when: false

- name: system setup | fail2ban | enable daemon
  tags: fail2ban,system,settings
  service:
    name: fail2ban
    enabled: yes
    state: started
  when: check_binary.rc == 0

- name: system setup | fail2ban | generate jail.local file from template
  tags: fail2ban,system,settings
  template:
    src: fail2ban/jail_local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart_fail2ban
  when: check_binary.rc == 0

- name: system setup | fail2ban | generate sshd.local file from template
  tags: fail2ban,sshd,system,settings
  template:
    src: fail2ban/sshd_local.j2
    dest: /etc/fail2ban/sshd.local
    owner: root
    group: root
    mode: 0644
  notify: restart_fail2ban
  when: 
    - sshd
    - check_binary.rc == 0