- name: system setup | firewall | open incoming ssh (suse)
  tags: firewall,system,settings,ssh,openssh
  firewalld:
    zone: public
    service: ssh
    permanent: yes
    immediate: yes
    state: enabled
