- name: trigger package cache refresh if needed
  meta: flush_handlers

- name: system setup | microcode | install package for amd
  tags: amd,cpu,microcode,system setup
  package:
    name: "{{ amd_microcode_package }}"
  when:
    - amd_microcode_package is defined
    - ansible_processor is search('AMD')

- name: system setup | microcode | install package for intel
  tags: cpu,intel,microcode,system setup
  package:
    name: "{{ intel_microcode_package }}"
  when:
    - intel_microcode_package is defined
    - ansible_processor is search('Intel')