- name: System setup | Install scheduled reboot timer
  ansible.builtin.template:
    src: reboot_timer.j2
    dest: /etc/systemd/system/scheduled-reboot.timer
    owner: root
    group: root
    mode: '0640'

- name: System setup | Enable scheduled reboot timer
  ansible.builtin.systemd:
    name: scheduled-reboot.timer
    enabled: true
