- name: System setup | Tailscale | Add repo (openSUSE MicroOS)
  community.general.zypper_repository:
    repo: https://pkgs.tailscale.com/stable/opensuse/tumbleweed/tailscale.repo
    auto_import_keys: true
    state: present
  notify: zypper_refresh
  when: ansible_distribution == "openSUSE MicroOS"

- name: Trigger package cache refresh if needed
  ansible.builtin.meta: flush_handlers

- name: System setup | Tailscale | Install
  ansible.builtin.package:
    name: tailscale
    state: present

- name: System setup | Tailscale | Check install state
  ansible.builtin.shell: command -v tailscale
  register: check_binary
  changed_when: false
  failed_when: false

- name: System setup | Tailscale | Enable tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  when: check_binary.rc == 0