- name: System setup | Tailscale | Add repo (Fedora Linux)
  ansible.builtin.copy:
    src: system_setup/tailscale_repo
    dest: /etc/yum.repos.d/tailscale.repo
    owner: root
    group: root
    mode: '0644'

- name: System setup | Tailscale | Install
  community.general.rpm_ostree_pkg:
    name: tailscale
    state: present

- name: System setup | Tailscale | Check install state
  ansible.builtin.command: command -v tailscale
  register: check_binary
  changed_when: false
  failed_when: false

- name: System setup | Tailscale | Enable tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  when: check_binary.rc == 0
